// LUXE MARKET - Vanilla JS
const SAMPLE_PRODUCTS=[{id:1,title:"Wireless Premium Headphones",category:"Electronics",subcategory:"Audio",description:"Experience crystal-clear sound with active noise cancellation. 40-hour battery life and premium comfort.",price_cents:29999,currency:"USD",images:{"1x":"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=800&fit=crop&auto=format"},featured:true,tags:["wireless","audio","premium"],rating:4.8},{id:2,title:"Minimalist Leather Backpack",category:"Fashion",subcategory:"Bags",description:"Handcrafted genuine leather backpack with laptop compartment.",price_cents:14999,currency:"USD",images:{"1x":"https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop&auto=format"},featured:false,tags:["leather","travel","professional"],rating:4.6},{id:3,title:"Smart Fitness Watch",category:"Electronics",subcategory:"Wearables",description:"Track your health with precision.",price_cents:19999,currency:"USD",images:{"1x":"https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=800&fit=crop&auto=format"},featured:true,tags:["fitness","smartwatch","health"],rating:4.7},{id:4,title:"Artisan Coffee Maker",category:"Home",subcategory:"Kitchen",description:"Brew barista-quality coffee at home.",price_cents:24999,currency:"USD",images:{"1x":"https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&h=800&fit=crop&auto=format"},featured:false,tags:["coffee","kitchen","artisan"],rating:4.9}];
const state={products:[],cart:[],wishlist:new Set(),selectedProduct:null,search:'',category:'All',priceRange:[0,300],sortBy:'featured',showCart:false,showFilters:false,heroIndex:0,modalQuantity:1};
const $=(s)=>document.querySelector(s);const $$=(s)=>document.querySelectorAll(s);const price=(c)=>`$${(c/100).toFixed(2)}`;
async function load(){try{const r=await fetch('http://localhost:3000/api/products');if(!r.ok)throw 0;const d=await r.json();state.products=d.products||d;}catch{state.products=SAMPLE_PRODUCTS;}render();}
function filtered(){let f=[...state.products];if(state.category!=='All')f=f.filter(p=>p.category===state.category);if(state.search){const q=state.search.toLowerCase();f=f.filter(p=>p.title.toLowerCase().includes(q)||p.tags?.some(t=>t.toLowerCase().includes(q)));}f=f.filter(p=>{const v=p.price_cents/100;return v>=state.priceRange[0]&&v<=state.priceRange[1];});f.sort((a,b)=>state.sortBy==='price-asc'?a.price_cents-b.price_cents:state.sortBy==='price-desc'?b.price_cents-a.price_cents:state.sortBy==='rating'?b.rating-a.rating:(b.featured?1:0)-(a.featured?1:0));return f;}
const cartCount=()=>state.cart.reduce((s,i)=>s+i.quantity,0);const cartTotal=()=>state.cart.reduce((s,i)=>s+i.quantity*i.price_cents,0);
function addToCart(p,q=1){const e=state.cart.find(i=>i.id===p.id);e?e.quantity+=q:state.cart.push({...p,quantity:q});toast('Added to cart!');render();}
function updateQty(id,q){if(q<=0){state.cart=state.cart.filter(i=>i.id!==id);}else{state.cart=state.cart.map(i=>i.id===id?{...i,quantity:q}:i);}render();}
function toast(m){const t=$('#toast-root');t.innerHTML=`<div class="fixed bottom-4 right-4 bg-slate-900 text-white px-6 py-4 rounded-xl shadow-2xl animate-slide-up">${m}</div>`;setTimeout(()=>t.innerHTML='',2000);}
function header(categories){return `<header class="sticky top-0 z-50 bg-white/80 backdrop-blur-xl border-b border-slate-200 shadow-sm"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div class="flex items-center justify-between h-16"><div class="flex items-center space-x-8"><h1 class="text-2xl font-bold bg-gradient-to-r from-teal-500 to-indigo-600 bg-clip-text text-transparent">LUXE MARKET</h1><nav class="hidden md:flex space-x-6">${categories.slice(0,4).map(c=>`<button data-cat="${c}" class="text-sm font-medium ${state.category===c?'text-teal-600':'text-slate-600 hover:text-slate-900'}">${c}</button>`).join('')}</nav></div><div class="flex items-center space-x-4"><div class="hidden sm:flex items-center bg-slate-100 rounded-full px-4 py-2"><input id="search" type="text" placeholder="Search products..." value="${state.search}" class="bg-transparent outline-none text-sm w-48"/></div><button id="toggle-filters" class="p-2 hover:bg-slate-100 rounded-lg md:hidden">☰</button><button id="open-cart" class="relative p-2 hover:bg-slate-100 rounded-lg">🛒${cartCount()?`<span class="absolute -top-1 -right-1 bg-teal-500 text-white text-xs rounded-full w-5 h-5 flex items-center justify-center font-bold">${cartCount()}</span>`:''}</button></div></div></div></header>`}
function hero(featured){const i=state.heroIndex%Math.max(1,featured.length);return `<div class="relative h-96 bg-gradient-to-r from-teal-500 via-indigo-600 to-purple-600 overflow-hidden"><div class="absolute inset-0 bg-black/20"></div>${featured.map((p,idx)=>`<div class="absolute inset-0 ${idx===i?'opacity-100':'opacity-0'} transition-opacity duration-1000" style="background-image:url(${p.images['1x']});background-size:cover;background-position:center"><div class="absolute inset-0 bg-gradient-to-r from-black/60 to-transparent"></div></div>`).join('')}<div class="relative h-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center"><div class="max-w-2xl"><h2 class="text-5xl font-bold text-white mb-4">Discover Premium Products</h2><p class="text-xl text-white/90 mb-8">Curated collection from trusted sellers worldwide</p><button id="shop-now" class="bg-white text-slate-900 px-8 py-3 rounded-full font-semibold hover:bg-slate-100">Shop Now</button></div></div><div class="absolute bottom-4 left-1/2 -translate-x-1/2 flex space-x-2">${featured.map((_,idx)=>`<button data-hero="${idx}" class="w-2 h-2 rounded-full ${idx===i?'bg-white w-8':'bg-white/50'}"></button>`).join('')}</div></div>`}
function filters(categories){return `<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8" id="products"><div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-8"><div class="flex flex-wrap gap-2">${categories.map(c=>`<button data-cat="${c}" class="px-4 py-2 rounded-full text-sm font-medium ${state.category===c?'bg-teal-500 text-white shadow-lg shadow-teal-500/30':'bg-white text-slate-600 hover:bg-slate-50 border border-slate-200'}">${c}</button>`).join('')}</div><div class="flex items-center gap-3"><div class="hidden md:flex items-center gap-2"><input id="pmin" type="number" min="0" max="300" value="${state.priceRange[0]}" class="w-24 px-3 py-2 rounded-lg border border-slate-200"/><span class="text-slate-400 text-sm">-</span><input id="pmax" type="number" min="0" max="300" value="${state.priceRange[1]}" class="w-24 px-3 py-2 rounded-lg border border-slate-200"/></div><select id="sort" class="px-4 py-2 rounded-lg border border-slate-200"><option value="featured" ${state.sortBy==='featured'?'selected':''}>Featured</option><option value="price-asc" ${state.sortBy==='price-asc'?'selected':''}>Price: Low to High</option><option value="price-desc" ${state.sortBy==='price-desc'?'selected':''}>Price: High to Low</option><option value="rating" ${state.sortBy==='rating'?'selected':''}>Highest Rated</option></select></div></div>${state.showFilters?`<div class="md:hidden mb-6 bg-white border border-slate-200 rounded-xl p-4 shadow-sm"><div class="mb-4"><h4 class="font-semibold text-slate-900 mb-2">Categories</h4><div class="flex flex-wrap gap-2">${categories.map(c=>`<button data-cat="${c}" class="px-3 py-1.5 rounded-full text-sm ${state.category===c?'bg-teal-500 text-white':'bg-slate-100 text-slate-700'}">${c}</button>`).join('')}</div></div><div class="mb-4"><h4 class="font-semibold text-slate-900 mb-2">Price Range ($)</h4><div class="flex items-center gap-2"><input id="mmin" type="range" min="0" max="300" value="${state.priceRange[0]}" class="w-1/2"/><input id="mmax" type="range" min="0" max="300" value="${state.priceRange[1]}" class="w-1/2"/></div><div class="text-xs text-slate-600 mt-2">$${state.priceRange[0]} - $${state.priceRange[1]}</div></div><div class="flex gap-2"><button id="close-filters" class="flex-1 py-2 rounded-lg border border-slate-200">Close</button><button id="apply-filters" class="flex-1 py-2 rounded-lg bg-teal-500 text-white">Apply</button></div></div>`:''}</div>`}
function productsGrid(list){return `<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">${list.map(p=>`<div class="group bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-2xl transition-all duration-300 hover:-translate-y-1"><div class="relative aspect-square overflow-hidden bg-slate-100"><img src="${p.images['1x']}" alt="${p.title}" class="w-full h-full object-cover"/><button data-wish="${p.id}" class="absolute top-3 right-3 p-2 bg-white/90 rounded-full shadow-lg">${state.wishlist.has(p.id)?'❤':'♡'}</button>${p.featured?`<div class="absolute top-3 left-3 bg-indigo-600 text-white text-xs font-bold px-3 py-1 rounded-full">FEATURED</div>`:''}</div><div class="p-5"><div class="flex items-center justify-between mb-2"><span class="text-xs font-semibold text-teal-600 uppercase tracking-wide">${p.category}</span><div class="text-sm font-semibold">⭐ ${p.rating}</div></div><h3 class="font-bold text-slate-900 mb-2 line-clamp-2">${p.title}</h3><p class="text-sm text-slate-600 mb-4 line-clamp-2">${p.description}</p><div class="flex items-center justify-between"><span class="text-2xl font-bold text-slate-900">${price(p.price_cents)}</span><div class="flex space-x-2"><button data-quick="${p.id}" class="p-2 bg-slate-100 rounded-lg" title="Quick View">🔍</button><button data-add="${p.id}" class="px-4 py-2 bg-teal-500 text-white rounded-lg">Add</button></div></div></div></div>`).join('')}</div></div>`}
function footer(){const y=new Date().getFullYear();return `<footer class="bg-slate-900 text-white mt-20"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12"><div class="grid md:grid-cols-4 gap-8"><div><h3 class="text-xl font-bold mb-4 bg-gradient-to-r from-teal-400 to-indigo-400 bg-clip-text text-transparent">LUXE MARKET</h3><p class="text-slate-400 text-sm">Premium products from trusted sellers worldwide.</p></div><div><h4 class="font-semibold mb-4">Shop</h4></div><div><h4 class="font-semibold mb-4">Support</h4></div><div><h4 class="font-semibold mb-4">Legal</h4></div></div><div class="border-t border-slate-800 mt-8 pt-8 text-center text-sm text-slate-400">© ${y} LUXE MARKET. All rights reserved.</div></div></footer>`}
function productModal(p){if(!p)return'';return `<div class="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4" data-close-modal><div class="bg-white rounded-3xl max-w-4xl w-full max-h-[90vh] overflow-y-auto shadow-2xl" onclick="event.stopPropagation()"><div class="sticky top-0 bg-white border-b border-slate-200 px-6 py-4 flex justify-between items-center z-10"><h2 class="text-xl font-bold">${p.title}</h2><button id="close-p" class="p-2 hover:bg-slate-100 rounded-lg">✕</button></div><div class="grid md:grid-cols-2 gap-8 p-6"><div><img src="${p.images['1x']}" class="w-full rounded-2xl shadow-xl"/></div><div><div class="flex items-center space-x-2 mb-4"><span class="px-3 py-1 bg-teal-100 text-teal-700 text-xs font-semibold rounded-full">${p.category}</span><div class="font-semibold">⭐ ${p.rating}</div></div><p class="text-slate-600 mb-6">${p.description}</p><div id="recs" class="mb-6"></div><div class="border-t border-slate-200 pt-6"><div class="flex items-center justify-between mb-6"><span class="text-3xl font-bold text-slate-900">${price(p.price_cents)}</span><div class="flex items-center space-x-3"><button id="q-" class="p-2 border rounded-lg">-</button><span id="qv" class="font-semibold w-8 text-center">${state.modalQuantity}</span><button id="q+" class="p-2 border rounded-lg">+</button></div></div><button id="add-modal" class="w-full py-4 bg-gradient-to-r from-teal-500 to-indigo-600 text-white rounded-xl font-bold">Add to Cart</button></div></div></div></div>`}
function cartDrawer(){if(!state.showCart)return'';return `<div class="fixed inset-0 bg-black/40 backdrop-blur-sm z-50" data-close-cart><div class="absolute right-0 top-0 h-full w-full max-w-md bg-white shadow-2xl overflow-y-auto" onclick="event.stopPropagation()"><div class="sticky top-0 bg-white border-b border-slate-200 px-6 py-4 flex justify-between items-center z-10"><h2 class="text-xl font-bold">Shopping Cart (${cartCount()})</h2><button id="close-c" class="p-2 hover:bg-slate-100 rounded-lg">✕</button></div>${state.cart.length?`<div class="p-6 space-y-4">${state.cart.map(i=>`<div class="flex gap-4 bg-slate-50 rounded-xl p-4"><img src="${i.images['1x']}" class="w-20 h-20 object-cover rounded-lg"/><div class="flex-1"><h3 class="font-semibold text-sm mb-1">${i.title}</h3><p class="text-slate-600 text-sm mb-2">${price(i.price_cents)}</p><div class="flex items-center space-x-2"><button data-dec="${i.id}" class="p-1 border rounded">-</button><span class="text-sm font-semibold w-8 text-center">${i.quantity}</span><button data-inc="${i.id}" class="p-1 border rounded">+</button><button data-rem="${i.id}" class="ml-auto p-1 text-red-500">🗑</button></div></div></div>`).join('')}</div><div class="sticky bottom-0 bg-white border-t border-slate-200 p-6"><div class="space-y-2 mb-4"><div class="flex justify-between text-sm"><span class="text-slate-600">Subtotal</span><span class="font-semibold">${price(cartTotal())}</span></div><div class="flex justify-between text-sm"><span class="text-slate-600">Shipping</span><span class="font-semibold text-teal-600">FREE</span></div><div class="flex justify-between text-lg font-bold pt-2 border-t border-slate-200"><span>Total</span><span>${price(cartTotal())}</span></div></div><button id="checkout" class="w-full py-4 bg-gradient-to-r from-teal-500 to-indigo-600 text-white rounded-xl font-bold">Proceed to Checkout →</button></div>`:`<div class="flex flex-col items-center justify-center h-64 text-slate-400">🛒<p>Your cart is empty</p></div>`}</div></div>`}
function checkout(){if(!state.checkout)return'';return `<div class="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4"><div class="bg-white rounded-3xl max-w-2xl w-full max-h-[90vh] overflow-y-auto shadow-2xl"><div class="sticky top-0 bg-white border-b border-slate-200 px-6 py-4 flex justify-between items-center z-10"><h2 class="text-xl font-bold">Checkout</h2><button id="close-co" class="p-2 hover:bg-slate-100 rounded-lg">✕</button></div><div class="p-6"><div class="mb-8"><h3 class="font-semibold mb-4">Contact Information</h3><div class="space-y-4"><input class="w-full px-4 py-3 border rounded-lg" placeholder="Full Name"/><input class="w-full px-4 py-3 border rounded-lg" placeholder="Email Address"/><input class="w-full px-4 py-3 border rounded-lg" placeholder="Phone Number"/></div></div><div class="mb-8"><h3 class="font-semibold mb-4">Shipping Address</h3><div class="space-y-4"><input class="w-full px-4 py-3 border rounded-lg" placeholder="Street Address"/><div class="grid grid-cols-2 gap-4"><input class="w-full px-4 py-3 border rounded-lg" placeholder="City"/><input class="w-full px-4 py-3 border rounded-lg" placeholder="Zip Code"/></div><input class="w-full px-4 py-3 border rounded-lg" placeholder="Country"/></div></div><div class="mb-8 bg-slate-50 rounded-xl p-4"><h3 class="font-semibold mb-4">Order Summary</h3>${state.cart.map(i=>`<div class="flex justify-between text-sm"><span class="text-slate-600">${i.title} × ${i.quantity}</span><span class="font-semibold">${price(i.price_cents*i.quantity)}</span></div>`).join('')}<div class="flex justify-between pt-2 border-t font-bold"><span>Total</span><span>${price(cartTotal())}</span></div></div><div class="grid grid-cols-1 sm:grid-cols-2 gap-3"><button id="place" class="w-full py-3 bg-gradient-to-r from-teal-500 to-indigo-600 text-white rounded-xl font-bold">Place Order</button><button id="pay-stripe" class="w-full py-3 bg-black text-white rounded-xl font-bold">Pay with Stripe</button></div></div></div></div>`}
function app(){const cats=['All',...new Set(state.products.map(p=>p.category))];const feat=state.products.filter(p=>p.featured);const list=filtered();return `${header(cats)}${hero(feat)}${filters(cats)}${productsGrid(list)}${footer()}`}
function render(){$('#app').innerHTML=app();$('#product-modal-root').innerHTML=productModal(state.selectedProduct);$('#cart-drawer-root').innerHTML=cartDrawer();$('#checkout-modal-root').innerHTML=checkout();bind();bindModal();bindCart();bindCheckout();}
function bind(){$$('#app [data-cat]').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.cat;render();}));const s=$('#app #search');if(s)s.addEventListener('input',e=>{state.search=e.target.value;render();});const tf=$('#app #toggle-filters');if(tf)tf.addEventListener('click',()=>{state.showFilters=!state.showFilters;render();});const oc=$('#app #open-cart');if(oc)oc.addEventListener('click',()=>{state.showCart=true;render();});const sn=$('#app #shop-now');if(sn)sn.addEventListener('click',()=>{document.getElementById('products')?.scrollIntoView({behavior:'smooth'});});$$('#app [data-hero]').forEach(b=>b.addEventListener('click',()=>{state.heroIndex=Number(b.dataset.hero)||0;render();}));const sort=$('#app #sort');if(sort)sort.addEventListener('change',e=>{state.sortBy=e.target.value;render();});const pmin=$('#app #pmin');const pmax=$('#app #pmax');if(pmin)pmin.addEventListener('change',e=>{const v=Math.max(0,Math.min(300,Number(e.target.value)));state.priceRange=[Math.min(v,state.priceRange[1]),state.priceRange[1]];render();});if(pmax)pmax.addEventListener('change',e=>{const v=Math.max(0,Math.min(300,Number(e.target.value)));state.priceRange=[state.priceRange[0],Math.max(v,state.priceRange[0])];render();});const mmin=$('#app #mmin');const mmax=$('#app #mmax');if(mmin)mmin.addEventListener('input',e=>{const v=Number(e.target.value);state.priceRange=[Math.min(v,state.priceRange[1]),state.priceRange[1]];});if(mmax)mmax.addEventListener('input',e=>{const v=Number(e.target.value);state.priceRange=[state.priceRange[0],Math.max(v,state.priceRange[0])];});const cf=$('#app #close-filters');if(cf)cf.addEventListener('click',()=>{state.showFilters=false;render();});const af=$('#app #apply-filters');if(af)af.addEventListener('click',()=>{state.showFilters=false;render();});$$('#app [data-wish]').forEach(b=>b.addEventListener('click',()=>{const id=Number(b.dataset.wish);state.wishlist.has(id)?state.wishlist.delete(id):state.wishlist.add(id);render();}));$$('#app [data-quick]').forEach(b=>b.addEventListener('click',()=>{state.selectedProduct=state.products.find(p=>p.id===Number(b.dataset.quick));state.modalQuantity=1;render();}));$$('#app [data-add]').forEach(b=>b.addEventListener('click',()=>{const p=state.products.find(p=>p.id===Number(b.dataset.add));addToCart(p,1);}));if(!state._hero){state._hero=setInterval(()=>{const feat=state.products.filter(p=>p.featured);if(feat.length){state.heroIndex=(state.heroIndex+1)%feat.length;render();}},5000);} }
function bindModal(){const r=$('#product-modal-root');if(!r.innerHTML)return;r.querySelector('[data-close-modal]')?.addEventListener('click',()=>{state.selectedProduct=null;render();});r.querySelector('#close-p')?.addEventListener('click',()=>{state.selectedProduct=null;render();});const qm=r.querySelector('#q-');const qp=r.querySelector('#q+');const qv=r.querySelector('#qv');if(qm)qm.addEventListener('click',()=>{state.modalQuantity=Math.max(1,state.modalQuantity-1);qv.textContent=state.modalQuantity;});if(qp)qp.addEventListener('click',()=>{state.modalQuantity+=1;qv.textContent=state.modalQuantity;});r.querySelector('#add-modal')?.addEventListener('click',()=>{addToCart(state.selectedProduct,state.modalQuantity);state.selectedProduct=null;render();});
  // Load recommendations
  const recs = r.querySelector('#recs');
  if (recs && state.selectedProduct) {
    fetch(`http://localhost:3000/api/recommendations?productId=${state.selectedProduct.id}`)
      .then(r=>r.json()).then(d=>{
        recs.innerHTML = `<h4 class="font-semibold mb-2">You may also like</h4><div class="grid grid-cols-2 gap-3">${(d.products||[]).map(p=>`<div class="text-sm"><img src="${p.images['1x']}" class="w-full h-24 object-cover rounded-lg mb-1"/><div>${p.title}</div><div class="text-slate-600">${price(p.price_cents)}</div></div>`).join('')}</div>`;
      }).catch(()=>{});
  }
}
function bindCart(){const r=$('#cart-drawer-root');if(!r.innerHTML)return;r.querySelector('[data-close-cart]')?.addEventListener('click',()=>{state.showCart=false;render();});r.querySelector('#close-c')?.addEventListener('click',()=>{state.showCart=false;render();});r.querySelectorAll('[data-dec]').forEach(b=>b.addEventListener('click',()=>{const id=Number(b.dataset.dec);const it=state.cart.find(i=>i.id===id);if(it)updateQty(id,it.quantity-1);}));r.querySelectorAll('[data-inc]').forEach(b=>b.addEventListener('click',()=>{const id=Number(b.dataset.inc);const it=state.cart.find(i=>i.id===id);if(it)updateQty(id,it.quantity+1);}));r.querySelectorAll('[data-rem]').forEach(b=>b.addEventListener('click',()=>{const id=Number(b.dataset.rem);state.cart=state.cart.filter(i=>i.id!==id);render();}));r.querySelector('#checkout')?.addEventListener('click',()=>{state.showCart=false;state.checkout=true;render();});}
function bindCheckout(){const r=$('#checkout-modal-root');if(!r.innerHTML)return;r.querySelector('#close-co')?.addEventListener('click',()=>{state.checkout=false;render();});r.querySelector('#place')?.addEventListener('click',async()=>{try{await fetch('http://localhost:3000/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:state.cart,total_cents:cartTotal()})});}catch{}state.checkout=false;state.cart=[];toast('Order placed successfully! 🎉');render();});
  const pay=r.querySelector('#pay-stripe');
  if (pay) pay.addEventListener('click', async()=>{
    try{
      const res = await fetch('http://localhost:3000/api/pay/checkout-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:state.cart})});
      const data = await res.json();
      if (data.url) { window.location.href = data.url; }
      else toast('Stripe not configured');
    }catch{ toast('Payment failed to initialize'); }
  });
}
load();
